language: java
jdk:
- openjdk11
env:
  matrix:
  - SAMPLE=spring/AnnotationConfigApplicationContext
script:
- cd $SAMPLE
- mvn --errors --batch-mode clean org.jacoco:jacoco-maven-plugin:prepare-agent verify
  sonar:sonar -Dsonar.projectKey=masooh_devll-samples
