language: java
jdk:
- openjdk8
- openjdk11
env:
  matrix:
  - SAMPLE=spring/AnnotationConfigApplicationContext
addons:
  sonarcloud:
    organization: "masooh"
    token:
      secure: "TU+mC0yPFYrEjqMhyoKDoo2EZ46ntdGQ3EbVp14SAM62LcsxKA00akcR+dwpwgoNf7mz8BzSPWyQ+JVRJPZIYy7jeKDggF4Cy9+yXpMCMOXv9/HfXWnZvFmnQLQlGOoPkUnt3BViB4QHS8gG4GJDI2teN6iwtnCYBnKmNS67RvyzKwxI1YX+nZZFn5vrVWgb6bJPgMSX9Cwkpd6KRsCGU0CDihzjjAD0TfuRCaSMo+mZ/BmWSH0kiEO71ATjEz0gOt4mZ/ZBzp+kN+nIUPy/+TmCVs0Yx7Y1BRsQMd0dH6iLhghfbeYpNI1Q7oHM2dJc4sTJ6cjYXicohqOkgpCOwslhI0NFeylP7jG2V+NBmBtNlL4GXqgvrZR3vVp03EWiXqg4FmJYxUoOhms1AJs0PRWL6v4QmW5fNG542UCjaxHn4LMqhlivWoFmbxiplGQx0sbEdN2D5hylOLzxtZFjziWR5qhDB4XjGfKoZidiouLJahxItzlTbsKwXZF2DavxVAaCTZAYXLs0miiSTUm018i97T/u3sho32BkC4W/vkvT0QF9BHKkT6KZPjJQUmnqtq91wE9oMU2SfQBFASPtQtxqox/u9JxzolGtCOQbNAYX+p2hGcHYN10xPvmmC4o6abHIJdRDPmIKgrhp9e0J4ck/fQUaXtjYVOmXbgjggmE="
script:
- cd $SAMPLE
- mvn --errors --batch-mode clean org.jacoco:jacoco-maven-plugin:prepare-agent verify
  sonar:sonar -Dsonar.projectKey=masooh_devll-samples
