@startuml
participant x
box Spring Boot ApplicationTests
    participant SpringBootTestContextBootstrapper
    participant SpringBootContextLoader
end box
box Spring Boot
    participant SpringApplication
end box
box Spring
    participant GenericWebApplicationContext
end box

x -> SpringBootTestContextBootstrapper: processMergedContextConfiguration()
SpringBootTestContextBootstrapper -> SpringBootTestContextBootstrapper: getOrFindConfigurationClasses()
note over SpringBootTestContextBootstrapper
    // Scan nach @SpringBootConfiguration
    new AnnotatedClassFinder(SpringBootConfiguration.class)
    				.findFromClass(mergedConfig.getTestClass())
end note

x -> SpringBootContextLoader: loadContext()

activate SpringApplication
SpringBootContextLoader -> SpringApplication: run()
note over SpringApplication
""  .   ____          _            __ _ _""
"" /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \""
""( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \""
"" \\/  ___)| |_)| | | | | || (_| |  ) ) ) )""
""  '  |____| .__|_| |_|_| |_\__, | / / / /""
"" =========|_|==============|___/=/_/_/_/""
"" :: Spring Boot ::        (v2.1.6.RELEASE)""
end note

SpringApplication -> SpringApplication: prepareEnvironment()
activate ApplicationEnvironmentPreparedEvent
SpringApplication -> ApplicationEnvironmentPreparedEvent
ApplicationEnvironmentPreparedEvent -> ConfigFileApplicationListener: onApplicationEnvironmentPreparedEvent()
ConfigFileApplicationListener -> SpringFactoriesLoader: loadFactories(EnvironmentPostProcessor)


SpringApplication -> SpringApplication: prepareContext()
note right of SpringApplication
    applyInitializers()
    jeder ContextCustomizer wir zum ApplicationContextInitializer via ContextCustomizerAdapter
    -> contextCustomizer entspricht contextInitializer
end note

SpringApplication -> GenericWebApplicationContext: refresh()
GenericWebApplicationContext -> GenericWebApplicationContext: invokeBeanFactoryPostProcessors()
note over SpringApplication: Started ApplicationTests in 1307.8 seconds (JVM running for 7906.949)
@enduml